### PR TITLE
get version strings in CMake at compile time

### PR DESCRIPTION
**Pull request by Mark-Niemeyer**

### CODE REVIEW

**Comment by jarkenau** [comment]
How should this be used? I tried to add `version` to the arguments of the server executable in the `launch.json`

```json
"args": ["-c/seerep/src/seerep.cfg", "version"],
```

But no extra output resulted from it, am I missing something?

**Comment by Mark-Niemeyer** [comment]
> How should this be used? I tried to add `version` to the arguments of the server executable in the `launch.json`
> 
> ```json
> "args": ["-c/seerep/src/seerep.cfg", "version"],
> ```
> 
> But no extra output resulted from it, am I missing something?

You have to use `--version` or `-v`

**Review by jarkenau — DISMISSED** [review]
Wouldn't it also make sense if we print or log the version at each server startup? 

Otherwise lgtm :+1:

**Review by jarkenau — APPROVED** [review]
:+1:

**Pull request merged**
