### PR TITLE
Convert frame_ids which are not in specification with tf2

### LINKED ISSUE #321: Check for tf2 compatible frame_ids
After the migration from `tf` to `tf2` frame_ids are not allowed to change a leading `/` http://wiki.ros.org/tf2/Migration. We need to check for this requirement in SEEREP before tf2 lib components are used.

### PR DESCRIPTION
**Pull request by jarkenau**
Closes #321

### CODE REVIEW

**Comment by Mark-Niemeyer** [comment]
Do we also have to check the `TransformStamped` when we add them to the core directly if a new tf is added via a gRPC service?

https://github.com/agri-gaia/seerep/blob/4a570f18ee8be7ca2c80f96f5c87c2c3a4d17b92/seerep_srv/seerep_core/src/core.cpp#L161-L165

**Comment by jarkenau** [comment]
> Do we also have to check the `TransformStamped` when we add them to the core directly if a new tf is added via a gRPC service?
> 
> https://github.com/agri-gaia/seerep/blob/4a570f18ee8be7ca2c80f96f5c87c2c3a4d17b92/seerep_srv/seerep_core/src/core.cpp#L161-L165

The transformation will not be added to the tf2 buffer, but it remains unnoticed since we don't check the return value of `setTransform`.
https://github.com/agri-gaia/seerep/blob/4a570f18ee8be7ca2c80f96f5c87c2c3a4d17b92/seerep_srv/seerep_core/src/core_tf.cpp#L116

Further, I have the problem, that I can't find a suitable location for a function which makes frame_ids tf2 compatible since there is no common base class for the core (`core.cpp or core_tf.cpp` and hdf5 interface (`hdf5_core_general`).

**Comment by Mark-Niemeyer** [comment]
> > Do we also have to check the `TransformStamped` when we add them to the core directly if a new tf is added via a gRPC service?
> > https://github.com/agri-gaia/seerep/blob/4a570f18ee8be7ca2c80f96f5c87c2c3a4d17b92/seerep_srv/seerep_core/src/core.cpp#L161-L165
> 
> The transformation will not be added to the tf2 buffer, but it remains unnoticed since we don't check the return value of `setTransform`.
> 
> https://github.com/agri-gaia/seerep/blob/4a570f18ee8be7ca2c80f96f5c87c2c3a4d17b92/seerep_srv/seerep_core/src/core_tf.cpp#L116
> 
> Further, I have the problem, that I can't find a suitable location for a function which makes frame_ids tf2 compatible since there is no common base class for the core (`core.cpp or core_tf.cpp` and hdf5 interface (`hdf5_core_general`).

`core_tf` has access to `Hdf5CoreTf` which is a child of `hdf5_core_general`

https://github.com/agri-gaia/seerep/blob/ba7ae9d4bd78f9dafffb9c057cf9778b23d6f142/seerep_srv/seerep_core/include/seerep_core/core_tf.h#L127

**Review by Mark-Niemeyer — APPROVED** [review]

**Comment by jarkenau** [comment]
I'm not too happy with the tf2 check in the core (https://github.com/agri-gaia/seerep/pull/322/commits/5426b60540a9ce5feab75a807f159e97e79c27b6), since we should do it when converting to the core messages, e.g. https://github.com/agri-gaia/seerep/blob/92021dcc51a7106a24c3e8c08859ec93814e6ddb/seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp#L541

Problem is that that is class is definitely not connected to anything other than the `core_msg` and `fb/pb_msgs`.

**Review by Mark-Niemeyer — APPROVED** [review]

**Pull request merged**
